language: ruby
script: rspec -f d

rvm:

  - 1.9
  - 2.0
  - 2.1
  - jruby-19mode

  - ruby-head
  - jruby-head

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
